name: Build and Jekyll site and run htmlproofer

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-site:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Fetch main
        run: |
          git fetch origin main --depth 1
          git branch

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically

      - name: Build with Jekyll
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Check links with lychee
        id: lychee
        uses: lycheeverse/lychee-action@v2.3.0
        with:
          fail: true
          args: --verbose --no-progress _site/*.html
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Check HTML using htmlproofer
        uses: chabad360/htmlproofer@v2
        with:
          directory: "_site"
          arguments: |
            --ignore-files "/.+\/_posts\/README.md"
            --checks "Images,Scripts"

      # TODO: remove before merge, for testing
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: pyos-infrastructure
          SLACK_COLOR: '#00FF00'
          SLACK_MESSAGE: "This is a test of the GitHub Actions Slack Notification."
          SLACK_TOKEN: ${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}
